In [1]:
from transformers import pipeline

c:\Users\LG\Desktop\project\POSCO-Holdings\new_env\Lib\site-packages\tqdm\auto.py:21: TqdmWarning: IProgress not found. Please update jupyter and ipywidgets. See https://ipywidgets.readthedocs.io/en/stable/user_install.html
  from .autonotebook import tqdm as notebook_tqdm


In [2]:
import torch

In [3]:
classifier = pipeline("sentiment-analysis")

No model was supplied, defaulted to distilbert/distilbert-base-uncased-finetuned-sst-2-english and revision 714eb0f (https://huggingface.co/distilbert/distilbert-base-uncased-finetuned-sst-2-english).
Using a pipeline without specifying a model name and revision in production is not recommended.
c:\Users\LG\Desktop\project\POSCO-Holdings\new_env\Lib\site-packages\huggingface_hub\file_download.py:143: UserWarning: `huggingface_hub` cache-system uses symlinks by default to efficiently store duplicated files but your machine does not support them in C:\Users\LG\.cache\huggingface\hub\models--distilbert--distilbert-base-uncased-finetuned-sst-2-english. Caching files will still work but in a degraded version that might require more space on your disk. This warning can be disabled by setting the `HF_HUB_DISABLE_SYMLINKS_WARNING` environment variable. For more details, see https://huggingface.co/docs/huggingface_hub/how-to-cache#limitations.
To support symlinks on Windows, you either need to 

In [4]:
classifier(["I want to go home."])

[{'label': 'POSITIVE', 'score': 0.9989783763885498}]

In [5]:
classifier(["I love you"])

[{'label': 'POSITIVE', 'score': 0.9998656511306763}]

In [6]:
classifier(["안녕하세요."])

[{'label': 'POSITIVE', 'score': 0.9321741461753845}]

In [7]:
classifier(["I love you", "I hate you"])

[{'label': 'POSITIVE', 'score': 0.9998656511306763},
 {'label': 'NEGATIVE', 'score': 0.9991129040718079}]

In [8]:
classifier = pipeline("zero-shot-classification")

No model was supplied, defaulted to facebook/bart-large-mnli and revision d7645e1 (https://huggingface.co/facebook/bart-large-mnli).
Using a pipeline without specifying a model name and revision in production is not recommended.
c:\Users\LG\Desktop\project\POSCO-Holdings\new_env\Lib\site-packages\huggingface_hub\file_download.py:143: UserWarning: `huggingface_hub` cache-system uses symlinks by default to efficiently store duplicated files but your machine does not support them in C:\Users\LG\.cache\huggingface\hub\models--facebook--bart-large-mnli. Caching files will still work but in a degraded version that might require more space on your disk. This warning can be disabled by setting the `HF_HUB_DISABLE_SYMLINKS_WARNING` environment variable. For more details, see https://huggingface.co/docs/huggingface_hub/how-to-cache#limitations.
To support symlinks on Windows, you either need to activate Developer Mode or to run Python as an administrator. In order to activate developer mode, see

In [9]:
import torch

In [10]:
import torch
print(torch.cuda.is_available())  # True면 GPU 사용 가능


False


In [13]:
classifier(
    "This is a course about the pipeline.",
    candidate_labels=["education", "politics", "business", "entertainment"]
)

{'sequence': 'This is a course about the pipeline.',
 'labels': ['business', 'education', 'politics', 'entertainment'],
 'scores': [0.7287567257881165,
  0.20385831594467163,
  0.03601036220788956,
  0.031374555081129074]}

In [14]:
import numpy as np

In [16]:
from sklearn.linear_model import LogisticRegression

In [17]:
X = np.array([[2], [4], [6], [8], [10]])

In [21]:
y = np.array([5, 9, 13, 17, 21])

In [19]:
X
Y

array([ 5,  9, 13, 17, 21])

In [20]:
X

array([[ 2],
       [ 4],
       [ 6],
       [ 8],
       [10]])

In [22]:
linear_regression = LogisticRegression()
linear_regression.fit(X, y)
pred = linear_regression.predict([[12]])

In [23]:
print(pred)

[21]


In [24]:
linear_regression.coef_

array([[-9.12646194e-01],
       [-3.76472689e-01],
       [-2.85755425e-05],
       [ 3.76539794e-01],
       [ 9.12607665e-01]])

In [25]:
linear_regression.intercept_

array([ 4.62505781,  2.72079418,  0.77765647, -1.79730672, -6.32620173])

In [26]:
hour_columns

NameError: name 'hour_columns' is not defined